Color Changes for Advanced Accessibility Standards
lat9/ZCA-Bootstrap-Template pull request #251
Opened 2023-06-28 21:10 UTC by dbltoe

The option to change the background color of Home, Log In, etc. when hovering over them was not included in the original listing. The existing stylesheet color of #333333 is more than sufficient but if the owner changes the color scheme of the navbar there's no easy option to change this setting.

As to the other color changes, more sophisticated testing methods actually require a higher color contrast for "action" text like links, buttons, etc.

This reflects the changes needed to comply with those better-defined rules.

2023-06-29 03:15 UTC, dennisns7d commented
Noting that the version-specific upgrade code in `init_bc_config_install_or_upgrade.php` needs to modified to properly update to 3.5.3, especially the two constants that are being renamed.

2023-06-29 15:42 UTC, dbltoe commented
Should I also fix lines 288 thru 297 to correct those errors and use changed versus added for the 3.5.3 version.

Doing another test today logged in as the customer, I also found that .alert-info is incorrect and not available for user manipulation.  That would only show if it is on the admin's screen but, as long as I am making the other changes.....

It involves color, background-color, and border-color.

What about 3.5.2 listings after line 800?

Thoughts\?

2023-06-29 20:13 UTC, dennisns7d commented
This may be a good time to fix lines 288 thru 297. Also consider the following constants to be consistent:
- ZCA_BUTTON_PAGEINATION_COLOR, ZCA_BUTTON_PAGEINATION_COLOR_HOVER
- ZCA_HEADER_NAVBAR_BUTTON_COLOR, ZCA_HEADER_NAVBAR_BUTTON_COLOR_HOVER
A 'changed' value as well as an 'old_key' value may be useful in changing old constant names to new names.

What I envision for the version-specific upgrade code after line 800 is something like:
`    case !defined('ZCA_BOOTSTRAP_COLORS_VERSION'):                      //-Fall-through, essentially v3.5.2 upgrade
    case version_compare(ZCA_BOOTSTRAP_COLORS_VERSION, '3.5.2', '<'):
        // insert entries added in 3.5.2
    case version_compare(ZCA_BOOTSTRAP_COLORS_VERSION, '3.5.2', '-'):  // Fall-through from above.
        // change configuration_key for constant names changed in 3.5.3
        // insert entries added in 3.5.3
        // update configuration_title, configuration_description, and sort_order to current values for all entries
    default: Fall-through from above`

2023-06-30 00:37 UTC, lat9 requested changes
At a minimum, that commentary needs correction.  I'm still noodling on the name-change and the potential issues it could cause.

2023-06-30 00:37 UTC, lat9 commented on includes/templates/bootstrap/css/stylesheet_zca_colors.php
> +    // Added in v3.5.3.
It'll be changed in v3.6.0, not 3.5.3.

2023-06-30 00:37 UTC, lat9 commented on includes/templates/bootstrap/css/stylesheet_zca_colors.php
> +    background-color: <?php echo ZCA_BUTTON_BACKGROUND_COLOR_HOVER; ?>;
I'm not a big fan of this renaming.  I know it's more consistent, but if a site has provided additional styling using those colors' constants the site will be met with a PHP Warning (at best).

2023-06-30 00:39 UTC, lat9 requested changes

2023-06-30 00:39 UTC, lat9 commented on YOUR_ADMIN/includes/init_includes/init_bc_config_install_or_upgrade.php
> +        'ZCA_HEADER_NAVBAR_LINK_BACKGROUND_COLOR_HOVER' => [
This line needs to line up with the other configuration names (i.e. left 4 spaces).

2023-06-30 00:39 UTC, lat9 commented on YOUR_ADMIN/includes/init_includes/init_bc_config_install_or_upgrade.php
> +        'added' => '3.5.3',
It'll be added in 3.6.0, not 3.5.3.

2023-07-03 18:31 UTC, lat9 commented
Just push what you've got and update the referenced issue with the coloring you want for the alert-info.  I'll take it from here.

2023-07-03 18:49 UTC, dbltoe commented
SEE PR#255

2023-07-03 18:49 UTC, closed without merging