Update html_header.php
lat9/ZCA-Bootstrap-Template pull request #265
Opened 2023-07-13 13:54 UTC by brittainmark

Have updated html header to font Awesome 6
Corrected error that stopped preload working
change loads to loop rather than hard coded list

Have left in the fa4-shim as bootstrap was on fa-5 it is probably not required. will take out if you don't want it.

2023-07-13 14:27 UTC, lat9 commented
I'm not ready to deal with this for the current, almost ready, release.  I'll hold off any additional thoughts until the template's v3.7.0 is underway.

2023-07-13 15:28 UTC, brittainmark commented
Had missed out the no preload. Did it now so I did not forget.

2024-04-28 15:24 UTC, lat9 requested changes
You'll also need to 'rebase' on the current default branch.

2024-04-28 15:24 UTC, lat9 commented on includes/extra_datafiles/dist.site-specific-bootstrap-settings.php
> +//$bs4_no_preloading = true;
Let's keep with the current naming convention for variables here, use `$zca_no_preloading` and (like the other soft-settings) the value present here is the default (`false`).

2024-04-28 15:24 UTC, lat9 commented on includes/templates/bootstrap/common/html_header.php
> + * BOOTSTRAP v3.6.0
This will be for `3.7.0`.

2024-04-28 17:37 UTC, dennisns7d commented
Noting that the latest version of FA is 6.5.2.

2024-04-28 17:40 UTC, lat9 commented
> Noting that the latest version of FA is 6.5.2.

Good point, what about that, @brittainmark?

2024-04-28 17:45 UTC, lat9 commented
Also, please re-rebase on the v370 branch; that's where this change is destined.

2024-04-28 21:20 UTC, lat9 approved these changes
Thanks, @brittainmark, for these and other changes.

2024-04-28 21:21 UTC, merged