Changes required for accessibility page
lat9/ZCA-Bootstrap-Template pull request #325
Opened 2024-03-03 12:35 UTC by scottcwilson

2024-03-03 14:52 UTC, lat9 commented
I'll grant that I've not followed the incorporation into zc200, but shouldn't there be a means for a site to "not include" that page in the sitemap/information-sidebox even if the page exists?

2024-03-04 10:37 UTC, scottcwilson commented
You can hide it with a flag that exists in the new site_specific storefront file.  I have added a check if they wish to add this setting to their copy of the file.

2024-03-04 13:07 UTC, lat9 commented on includes/modules/sideboxes/bootstrap/information.php
> +if (defined('FILENAME_ACCESSIBILITY') && (!isset($flag_show_accessibility_sidebox_link) || $flag_show_accessibility_sidebox_link == 0)) {
How about simply `!empty()` on that soft setting?

2024-03-04 13:08 UTC, lat9 requested changes
Use `!empty()` in both places.

2024-03-04 13:57 UTC, scottcwilson commented
> Use `!empty()` in both places.

`!empty` won't work in older versions of Zen Cart because this flag is only set in the newest version of `includes/init_includes/init_common_elements.php`.  That's why I did it this way.

2024-03-04 14:48 UTC, drbyte commented
`empty($var)` === true in the following conditions:
- `$var` not defined
- `$var === 0`
- `$var == 0`
- `$var == '0'`
- `$var == ''`
- `$var === false`
- `$var === null`

Basically: falsey, null, empty, blank, missing

That's why we use it in a lot of places. Especially for backward compatibility.
(There are of course some cases where we 'do' need an `isset()` because we want to know that, but in the case of a flag that's only used for an on/off switch, it's moot.)

Doesn't work on "undefined constants" though. Those will throw an error about undefined constant before passing thru to empty().

2024-03-04 16:37 UTC, scottcwilson commented
So is this ready to merge then?

2024-03-04 18:58 UTC, dennisns7d commented
It appears to me that `!isset($flag_show_accessibility_sidebox_link) || $flag_show_accessibility_sidebox_link == 0)` reverses the desired boolean value when `$flag_show_accessibility_sidebox` is defined.
Shouldn't it be the same as the expression in `includes/init_includes/init_common_elements.php` - `(isset($flag_show_accessibility_sidebox_link)) ? (bool)$flag_show_accessibility_sidebox_link : true`?

2024-03-04 19:36 UTC, scottcwilson commented
@dennisns7d is correct in his first statement.  Thank you!

2024-03-04 20:07 UTC, lat9 commented
I'm still not liking this and still believe that `!empty()` is the right approach.  If the template's running on zc200, then the filename is defined and init_common_elements.php has defaulted the value to `(bool)true` if not previously defined, so the sidebox link will be displayed.

If running on zc157/zc158, then the site has to take additional actions (i.e. both defining that FILENAME_ACCESSIBILITY, setting the "soft" setting, copying over the `pages/accessibility` files as well as the associated language file.

2024-03-04 21:17 UTC, scottcwilson commented
Done.  Please merge.

2024-03-04 21:37 UTC, lat9 commented
Addresses issue #327.

2024-03-04 21:37 UTC, lat9 approved these changes

2024-03-04 21:38 UTC, merged