Accessabiliy issue order of headings
lat9/ZCA-Bootstrap-Template pull request #351
Opened 2024-04-03 14:33 UTC by brittainmark

Need to change itemTitle from <h5> to <p> to score 100 on accessability in google chrome

2024-04-04 13:54 UTC, lat9 requested changes
Thanks for taking care of all of the doc updates!  Just a couple of minor changes.

2024-04-04 13:54 UTC, lat9 commented on docs/bootstrap/readme.html
> +        <li>v3.6.5-beta3, 2024-04-03 (brittainmark)<ul>
This should be `lat9, brittainmark`.

2024-04-04 13:54 UTC, lat9 commented on docs/bootstrap/readme.html
> +    <p>Version 3.6.5, by lat9, drbyte, scottcwilson, marco-pm, dbltoe, dennisns7d, brittainmark, torvista, proseLA, daphilli224 and brittainmark</p>
You're already in the list; restore to the previous version.

2024-04-04 14:41 UTC, brittainmark commented
I think there are a number of these, do you want them one at a time or in one lot?

2024-04-04 14:52 UTC, lat9 approved these changes

2024-04-04 14:54 UTC, merged

2024-04-06 22:58 UTC, lat9 commented
This is associated with issue #352