Update tpl_columnar_display_carousel.php
lat9/ZCA-Bootstrap-Template pull request #455
Opened 2024-11-11 06:03 UTC by highburyeye

prevents PHP Deprecated: Implicit conversion from float 1.3333333333333333 to int loses precision clogging up logs

2025-01-02 19:40 UTC, lat9 requested changes
Please remove the `//TC fixed error` comments and I'll merge.

2025-01-05 09:25 UTC, highburyeye commented
done

On Fri, 3 Jan 2025 at 08:40, lat9 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please remove the //TC fixed error comments and I'll merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lat9/ZCA-Bootstrap-Template/pull/455#pullrequestreview-2528122798>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVXPAVHAQVOYUNHX5Z7ZWMT2IWI4FAVCNFSM6AAAAABRRDA4ZWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRYGEZDENZZHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-06 13:45 UTC, lat9 commented
See issue #462

2025-01-06 13:46 UTC, lat9 approved these changes

2025-01-06 13:51 UTC, merged